version: '3'

volumes:
  dockerRecipeBookData:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerRecipeBookDatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dockerRecipeBookDatabase
    networks:
      - backend

  springapi:
    image: openjdk:11-jre-slim
    container_name: springapi
    ports:
      - 8085:8085
    depends_on:
      - database
    volumes:
      - ./recipe-book/target/docker-recipe-book-api.jar:application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backend
      - frontend

  angular:
    container_name: recipe-ang
    build:
      context: ./recipe-book-frontend
      dockerfile: Dockerfile
    depends_on:
      - springapi
    ports:
      - '80:80'
    networks:
      - frontend





